# Generated by Django 4.0.4 on 2022-05-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('BookId', models.AutoField(primary_key=True, serialize=False)),
                ('BookName', models.CharField(max_length=500)),
                ('BookAuthor', models.CharField(max_length=500)),
                ('Genre', models.CharField(max_length=500)),
                ('BookStatus', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('GenreId', models.AutoField(primary_key=True, serialize=False)),
                ('GenreName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('StatetId', models.AutoField(primary_key=True, serialize=False)),
                ('StateName', models.CharField(max_length=500)),
            ],
        ),
    ]
