# Generated by Django 4.0.4 on 2022-05-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookListApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='states',
            old_name='StatetId',
            new_name='StateId',
        ),
    ]
